import { Event } from './../event';

export const weatherEvents: Event[] = [{
    id:1,
    title:"Light Rain, mild weather",
    text:"The morning sees a gentle sprinkling and the sky clears to a calm pleasent day.",
    monsters:false,
    name:"nicedday",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:2,
    title:"Light Rain, mild weather",
    text:"The morning sees a gentle sprinkling and the sky clears to a calm pleasent day.",
    monsters:false,
    name:"nicedday",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:3,
    title:"Hot, misty",
    text:"The day is hot and humid with no rain subtracting -4 from anyone wearing Heavy armor for their daliy Con checks and require 1 gallon more of water today for all players.",
    monsters:false,
    name:"hot day",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:4,
    title:"Hot, misty",
    text:"The day is hot and humid with no rain subtracting -4 from anyone wearing Heavy armor for their daliy Con checks and require 1 gallon more of water today for all players.",
    monsters:false,
    name:"hot day",
    rolls:0,   
    die:0,
    extra:0 
},
{
    id:5,
    title:"Hot, misty",
    text:"The day is hot and humid with no rain subtracting -4 from anyone wearing Heavy armor for their daliy Con checks and require 1 gallon more of water today for all players.",
    monsters:false,
    name:"hot day",
    rolls:0,   
    die:0,
    extra:0
},
{
    id:6,
    title:"Rain",
    text:"An easy rain falls all day providing opportunity for anyone witha Rain catcher to collect water.  ",
    monsters:false,
    name:"Rain",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:7,
    title:"Rain",
    text:"An easy rain falls all day providing opportunity for anyone witha Rain catcher to collect water.  ",
    monsters:false,
    name:"Rain",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:8,
    title:"Windy, Rainy Day.",
    text:"Winds blow in from the Sea bringing sheets of rain down sideways.  Visibility is limited to 100ft and ranged attacks carry a -2 penalty today.",
    monsters:false,
    name:"Rain",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:9,
    title:"Windy, Rainy Day.",
    text:"Winds blow in from the Sea bringing sheets of rain down sideways.  Visibility is limited to 100ft and ranged attacks carry a -2 penalty today.",
    monsters:false,
    name:"Wind and Rain",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:10,
    title:"Windy, Rainy Day.",
    text:"Winds blow in from the Sea bringing sheets of rain down sideways.  Visibility is limited to 100ft and ranged attacks carry a -2 penalty today.",
    monsters:false,
    name:"Wind and Rain",
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:11,
    title:"Pleasent day",
    text:"A warm sun finds its way between scattered white clouds that move swiftly across a blue sky..",
    monsters:false,
    name:'Pleasent Day',
    rolls:0,   
    die:0,
    extra:0, 
},
{
    id:12,
    title:"Pleasent day",
    text:"A warm sun finds its way between scattered white clouds that move swiftly across a blue sky..",
    monsters:false,
    name:"Pleasent Day",
    rolls:0,  
    die:0,
    extra:0, 
},
{
    id:13,
    title:"Pleasent day",
    text:"A warm sun finds its way between scattered white clouds that move swiftly across a blue sky..",
    monsters:false,
    name:"Pleasent Day",
    rolls:0,  
    die:0,
    extra:0, 
},
{
    id:14,
    title:"Pleasent day",
    text:"A warm sun finds its way between scattered white clouds that move swiftly across a blue sky..",
    monsters:false,
    name:"Pleasent Day",
    rolls:0,  
    die:0,
    extra:0, 
},
{
    id:14,
    title:"Pleasent day",
    text:"A warm sun finds its way between scattered white clouds that move swiftly across a blue sky..",
    monsters:false,
    name:"Pleasent Day",
    rolls:0,  
    die:0,
    extra:0, 
},

{
    id:15,
    title:"Intermittent Rain",
    text:"Scattered showers fall throughout the day beneath a blanket of thikc grey clouds.",
    monsters:false,
    name:"Intermittent Rain",
    rolls:0,  
    die:0,
    extra:0, 
},

{
    id:16,
    title:"Intermittent Rain",
    text:"Scattered showers fall throughout the day beneath a blanket of thikc grey clouds.",
    monsters:false,
    name:"Intermittent Rain",
    rolls:0,  
    die:0,
    extra:0, 
},

{
    id:17,
    title:"Thunder Storms",
    text:"Storms rack the island of Chult bringing down shets of rain from all angles.  Travel limited to half speed and travel by boat results in a swamped canoe after 1 hour.",
    monsters:false,
    name:"Thunder Storms",
    rolls:0,  
    die:0,
    extra:0, 
},

{
    id:18,
    title:"Thunder Storms",
    text:"Storms rack the island of Chult bringing down shets of rain from all angles.  Travel limited to half speed and travel by boat results in a swamped canoe after 1 hour.",
    monsters:false,
    name:"Thunder Storms",
    rolls:0,  
    die:0,
    extra:0, 
},

{
    id:19,
    title:"Thunder Storms",
    text:"Storms rack the island of Chult bringing down shets of rain from all angles.  Travel limited to half speed and travel by boat results in a swamped canoe after 1 hour.",
    monsters:false,
    name:"Thunder Storms",
    rolls:0,  
    die:0,
    extra:0, 
 
},
{
    id:20,
    title:"Tropical Storm",
    text:"Chultan weather brings its wrath down on the island whipping winds and rain at terrible speeds.  All players must make a DC 15 Con check or recieve a level of exhaustion.  Travel is impossible today on rivers and every hex crossed guarantees a level of exhaustion by foot.",
    monsters:false,
    name:"Tropical Storm",
    rolls:0,  
    die:0,
    extra:0, 
},



]