import { Event } from './event';
import { Component, OnInit } from '@angular/core';


export const beachEvents: Event[] = [
    {
        id: 1,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,


    },
    {
        id: 2,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,


    },
    {
        id: 3,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,


    },
    {
        id: 4,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,


    },
    {
        id: 5,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,


    },
    {
        id: 6,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,


    },
    {
        id: 7,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,


    },
    {
        id: 8,
        title: 'Artus Climber',
        text: "Artus CLimber with or without his saurial traveling companion DragonBait, can be encounterd almost anywhere.  He may use the ring of winter to save the characters.  He is friendly  ",
        monsters: true,
        name: "Artus Climber",
        rolls: 1,
        die: 1,
        extra: 0,


    },
    {
        id: 9,
        title: 'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters: false,
        name: "",
        rolls: 0,
        die: 0,
        extra: 0,

    },
    {
        id: 10,
        title: 'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters: false,
        name: "",
        rolls: 0,
        die: 0,
        extra: 0,

    },

    {
        id: 11,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0
    },

    {
        id: 12,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0
    },

    {
        id: 13,
        title: 'Allosaurus',
        text: 'Theparty scent atteracts 1d4-1 allorsaurus.  Any characters who succeed ona DC 15 Survival check find a safe place to hide, high branch, hole etc, where the "honkers" cant reach them',
        monsters: true,
        name: 'Allosaurus',
        rolls: 1,
        die: 4,
        extra: -1
    },
    {
        id: 14,
        title: 'Allosaurus',
        text: 'The party scent atteracts 1d4-1 allorsaurus.  Any characters who succeed ona DC 15 Survival check find a safe place to hide, high branch, hole etc, where the "honkers" cant reach them',
        monsters: true,
        name: 'Allosaurus',
        rolls: 1,
        die: 4,
        extra: -1
    },
    {
        id: 15,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 16,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 17,
        title: 'Plesiosuarus',
        text: 'Two plesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 18,
        title: 'Plesiosuarus',
        text: 'Twoplesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 19,
        title: 'Plesiosuarus',
        text: 'Twoplesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 20,
        title: 'Plesiosuarus',
        text: 'Twoplesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 21,
        title: 'Plesiosuarus',
        text: 'Twoplesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 22,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 23,
        title: 'Pternadon',
        text: 'A flock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 24,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 25,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 26,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 27,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 28,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 29,
        title: 'Quetzalcoatlus',
        text: 'A fight of 1d4 Quetzalcoatlus are spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Quetzalcoatlus ",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 30,
        title: 'Quetzalcoatlus',
        text: 'A fight of 1d4 Quetzalcoatlus are spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Quetzalcoatlus ",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 31,
        title: 'Quetzalcoatlus',
        text: 'A fight of 1d4 Quetzalcoatlus are spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Quetzalcoatlus",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 32,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters: true,
        name: "Velociraptor",
        rolls: 3,
        die: 6,
        extra: 0
    },
    {
        id: 33,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters: true,
        name: "Velociraptor",
        rolls: 3,
        die: 6,
        extra: 0
    },
    {
        id: 34,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters: true,
        name: "Velociraptor",
        rolls: 3,
        die: 6,
        extra: 0
    },
    {
        id: 35,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters: true,
        name: "Velociraptor",
        rolls: 3,
        die: 6,
        extra: 0
    },
    {
        id: 36,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters: true,
        name: "Velociraptor",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 37,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters: true,
        name: "Velociraptor",
        rolls: 3,
        die: 6,
        extra: 0
    },
    {
        id: 38,
        title: 'Dragon, Red',
        text: 'If he characters are within 50 miles of Wyrmheart Mine, they see the young red dragon known as Tzindeldor or Tinder circling over that location.  If they are farther away they see her flying in the direction of the mine.  The dragon ignores the party unless they do something to attract her attention.',
        monsters: true,
        name: "Young Red Dragon",
        rolls: 0,
        die: 0,
        extra: 1
    },
    {
        id: 39,
        title: 'Dragon, Red',
        text: 'If he characters are within 50 miles of Wyrmheart Mine, they see the young red dragon known as Tzindeldor or Tinder circling over that location.  If they are farther away they see her flying in the direction of the mine.  The dragon ignores the party unless they do something to attract her attention.',
        monsters: true,
        name: "Young Red Dragon",
        rolls: 0,
        die: 0,
        extra: 1
    },
    {
        id: 40,
        title: 'Dragon, Red',
        text: 'If he characters are within 50 miles of Wyrmheart Mine, they see the young red dragon known as Tzindeldor or Tinder circling over that location.  If they are farther away they see her flying in the direction of the mine.  The dragon ignores the party unless they do something to attract her attention.',
        monsters: true,
        name: "Young Red Dragon",
        rolls: 0,
        die: 0,
        extra: 1
    },
    {
        id: 41,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.' +
            "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check." +
            "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters: true,
        name: "Scout",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 42,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.' +
            "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check." +
            "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters: true,
        name: "Scout",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 43,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 44,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 45,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 46,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 47,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters: true,
        name: "guard",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 48,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters: true,
        name: "guard",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 49,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters: true,
        name: "guard",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 50,
        title: 'Flying Monkeys',
        text: 'Thesound of flapping wings heralds the arrival of 3d6 flying monkies which swoop through the adventurers in a wave of grasping hands and feet.  Each character must make a dc 12 dex save or lose a useful peice of gear.',
        monsters: true,
        name: "Flying Monkey",
        rolls: 3,
        die: 6,
        extra: 0,

    },
    {
        id: 51,
        title: 'Fling Monkeys',
        text: 'The sound of flapping wings heralds the arrival of 3d6 flying monkies which swoop through the adventurers in a wave of grasping hands and feet.  Each character must make a dc 12 dex save or lose a useful peice of gear.',
        monsters: true,
        name: "Flying Monkey",
        rolls: 3,
        die: 6,
        extra: 0,

    },
    {
        id: 52,
        title: 'Fling Monkeys',
        text: 'The sound of flapping wings heralds the arrival of 3d6 flying monkies which swoop through the adventurers in a wave of grasping hands and feet.  Each character must make a dc 12 dex save or lose a useful peice of gear.',
        monsters: true,
        name: "Flying Monkey",
        rolls: 3,
        die: 6,
        extra: 0,

    },
    {
        id: 53,
        title: 'Fling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 54,
        title: 'Flying Snakes',
        text: 'Rol any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 55,
        title: 'Flying Snakes',
        text: 'Rol any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 56,
        title: 'Frost Giants',
        text: 'Thecharacters hear the sound of huge creatures stomping through the wilderness.  If they follow the noise they encounter a party of 3 frost giants searching the jungle accompanied by 1d4-2 winter wolves.  Roll a d10, on 9 or 10 this is Drufis search party (page 64 TOA book).  The frost giants are looking for Artus Climber and the ring of winter and they may help characters who provide useful information.  They immediately attack anyone who witholds information or who threaten to reveal their location to the flaming fist.  They carry no treasure',
        monsters: true,
        name: "Frost Giant",
        rolls: 0,
        die: 0,
        extra: 3
    },
    {
        id: 57,
        title: 'Frost Giants',
        text: 'Thecharacters hear the sound of huge creatures stomping through the wilderness.  If they follow the noise they encounter a party of 3 frost giants searching the jungle accompanied by 1d4-2 winter wolves.  Roll a d10, on 9 or 10 this is Drufis search party (page 64 TOA book).  The frost giants are looking for Artus Climber and the ring of winter and they may help characters who provide useful information.  They immediately attack anyone who witholds information or who threaten to reveal their location to the flaming fist.  They carry no treasure',
        monsters: true,
        name: "Frost Giant",
        rolls: 0,
        die: 0,
        extra: 3
    },
    {
        id: 58,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 59,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 60,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 61,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 62,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 63,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 64,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 65,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 66,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 67,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 68,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters: true,
        name: "Lizardfolk",
        rolls: 2,
        die: 4,
        extra: 0,
    },
    {
        id: 69,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters: true,
        name: "Lizardfolk",
        rolls: 2,
        die: 4,
        extra: 0,
    },
    {
        id: 70,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters: true,
        name: "Lizardfolk",
        rolls: 2,
        die: 4,
        extra: 0,
    },
    {
        id: 71,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters: true,
        name: "Lizardfolk",
        rolls: 2,
        die: 4,
        extra: 0,
    },
    {
        id: 72,
        title: 'Red Wizard',
        text: 'Thi group consists of 1 red wizard, LE, human mage, 1d6 guards, and 1d6 skeletons, all answerable to Velinda Shadowmantle.  If this encounter happens outside of the city of Omu, they are reinforcements on their way to the city.  If inside Omu the party is searching the citry for shrines (chapter 3).  They are not spoiling for a fight and if things look grim, they will surrender and offer up a crudely drawn map of Chult with the location of known undead hordes.',
        monsters: true,
        name: "Red Wizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 73,
        title: 'Red Wizard',
        text: 'This group consists of 1 red wizard, LE, human mage, 1d6 guards, and 1d6 skeletons, all answerable to Velinda Shadowmantle.  If this encounter happens outside of the city of Omu, they are reinforcements on their way to the city.  If inside Omu the party is searching the citry for shrines (chapter 3).  They are not spoiling for a fight and if things look grim, they will surrender and offer up a crudely drawn map of Chult with the location of known undead hordes.',
        monsters: true,
        name: "Red Wizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 74,
        title: 'Red Wizard',
        text: 'Thi group consists of 1 red wizard, LE, human mage, 1d6 guards, and 1d6 skeletons, all answerable to Velinda Shadowmantle.  If this encounter happens outside of the city of Omu, they are reinforcements on their way to the city.  If inside Omu the party is searching the citry for shrines (chapter 3).  They are not spoiling for a fight and if things look grim, they will surrender and offer up a crudely drawn map of Chult with the location of known undead hordes.',
        monsters: true,
        name: "Red Wizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 75,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 76,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 77,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 78,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 79,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 80,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 81,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 82,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 83,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 84,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 85,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters: true,
        name: "Stirge",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 86,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters: true,
        name: "Stirge",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 87,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters: true,
        name: "Stirge",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 88,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters: true,
        name: "Swarm of Bats",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 89,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters: true,
        name: "Swarm of Bats",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 90,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters: true,
        name: "Tabaxi Hunter",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 91,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters: true,
        name: "Tabaxi Hunter",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 92,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters: true,
        name: "Tabaxi Hunter",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 93,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters: true,
        name: "Tabaxi Hunter",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 94,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters: true,
        name: "Tabaxi Hunter",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 95,
        title: 'Tri-flower frond',
        text: 'If his encounter happens in the wild the party stumbles upon 1d4 Tri-flower fronds that appear as nomral plants.  If the encounter occurs while the characters are camped, the fronds sneak into camp and attempt to anesthitize the party with their orange blossoms, then kill them with their yellow and red blossoms.',
        monsters: true,
        name: "Tri-flower frond",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 96,
        title: 'Tri-flower frond',
        text: 'If his encounter happens in the wild the party stumbles upon 1d4 Tri-flower fronds that appear as nomral plants.  If the encounter occurs while the characters are camped, the fronds sneak into camp and attempt to anesthitize the party with their orange blossoms, then kill them with their yellow and red blossoms.',
        monsters: true,
        name: "Tri-flower frond",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 97,
        title: 'Tri-flower frond',
        text: 'If his encounter happens in the wild the party stumbles upon 1d4 Tri-flower fronds that appear as nomral plants.  If the encounter occurs while the characters are camped, the fronds sneak into camp and attempt to anesthitize the party with their orange blossoms, then kill them with their yellow and red blossoms.',
        monsters: true,
        name: "Tri-flower frond",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 98,
        title: 'Tri-flower frond',
        text: 'If his encounter happens in the wild the party stumbles upon 1d4 Tri-flower fronds that appear as nomral plants.  If the encounter occurs while the characters are camped, the fronds sneak into camp and attempt to anesthitize the party with their orange blossoms, then kill them with their yellow and red blossoms.',
        monsters: true,
        name: "Tri-flower frond",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 99,
        title: 'Tri-flower frond',
        text: 'If his encounter happens in the wild the party stumbles upon 1d4 Tri-flower fronds that appear as nomral plants.  If the encounter occurs while the characters are camped, the fronds sneak into camp and attempt to anesthitize the party with their orange blossoms, then kill them with their yellow and red blossoms.',
        monsters: true,
        name: "Tri-flower frond",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 100,
        title: 'Tri-flower frond',
        text: 'If his encounter happens in the wild the party stumbles upon 1d4 Tri-flower fronds that appear as nomral plants.  If the encounter occurs while the characters are camped, the fronds sneak into camp and attempt to anesthitize the party with their orange blossoms, then kill them with their yellow and red blossoms.',
        monsters: true,
        name: "Tri-flower frond",
        rolls: 1,
        die: 4,
        extra: 0,
    },
]





