import { Event } from './event';
import { Component, OnInit } from '@angular/core';


export const noUndeadEvents: Event[] = [
    {
        id:1,
        title:'Albino Dwarves',
        text:"The characters are ambushed by 1d4+3 Albino Dwarf Warriors that spring forth from a burrow.  Any character with a passive perception above 13 notices the dwarves, everyone else is surprised.  The dwarves prefer to knock out players and steal food, gold, gear rather than kill them.  They break off their attacks if anyone speaks Dwarvish or shows peaceful intentions.",
        monsters:true,
        name: "Albino Dwarf",
        rolls:1,
        die:4,
        extra:3,
        },
        
    
    {
        id:2,
        title:'Almiraj',
        text:"Almiraj are small bunny-unicorn things.  Amny character with a pass perception of 12 or higher spots 1d6 Almiraj 60 ft away.  The almiraj run away from any creature that they can see within 30 ft of them.  Any character who sccessfully traps an Almiraj can use an action to make a DC 14 animal handling check.  On success the Almiraj becomes tame an will not run away or attack unless it feels thretened or is harmed.",
        monsters:true,
           
        name: "Almiraj",
        rolls:1,
        die:6,
        extra:0,
    },
    {
        id:3,
        title:'Ape',
        text:"Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters:true,
    
        name: "Aarakocra",
        rolls:1,
        die:4,
        extra:1,
    },
    {
        id:4,
        title:'Ape',
        text:"Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters:true,
           
        name: "Ape",
        rolls:2,
        die:4,
        extra:0,
     },
    {
        id:5,
        title:'Artus Climber',
        text:"Artus CLimber with or without his saurial traveling companion DragonBait, can be encounterd almost anywhere.  He may use the ring of winter to save the characters.  He is friendly  ",
        monsters:true,
        name: "Artus Climber",
        rolls:1,
        die:1,
        extra:0,
        }
        
    ,
    {
        id:6,
        title:'Assassin Vine',
        text:"The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters:true,
        name: "Assassin Vine",
        rolls:2,
        die:4,
        extra:-1,
        },
    {
        id:7,
        title:'Assassin Vine',
        text:"The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters:true,
        name: "Assassin Vine",
        rolls:1,
        die:4,
        extra:-1,
            
        
    },
    {  
        id:8,
        title:'Axe Beaks',
        text:"A flock of 1d6 +3 Axe Beaks (big ass murder ostritch birds) come crashing through the jungle.  The parrty can hear them before they arrive but can see nothing until the birds are upons them slashing at everything within range. ",
        monsters:true,
        name: "Axe Beak",
        rolls:1,
        die:6,
        extra:3,
            
        
    },
     { id: 9,
        title:'Baboons ' ,
        text: 'A pack of 3d6 baboons take umbrage with the players entering their territory.  They can be distracted by tossing them each a days supply of food.  Otherwise they attack.',
        monsters:false,
        name:"Baboon",
        rolls:3,
        die:6,
        extra:0,
    
    } ,
      { id: 10,
        title:'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters:false,
        name:"",
        rolls:0,
        die:0,
        extra:0,
    
    } ,
    {   id: 11,
        title:'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters:false,
        name:"",
        rolls:0,
        die:0,
        extra:0,
    
    } ,
   
    { 
        id: 12,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters:true, 
        name:'Tribal Warrior',
        rolls:3,
        die:6,
        extra:0} ,

    { 
        id: 13,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters:true, 
        name:'Tribal Warrior',
        rolls:3,
        die:6,
        extra:0},
    { 
        id: 14,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters:true, 
        name:'Chwinga',
        rolls:1,
        die:1,
        extra:0
        },
    { 
        id: 15,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters:true, 
        name:'Chwinga',
        rolls:1,
        die:1,
        extra:0,
                }  ,
      { id: 16,
        title: 'Cyclops',
        text: 'A cyclops is heading towards his home in snapping turtle bay.  He is not looking for a fight but any sudden moves or hostility may trigger one.  The Cyclops knows the region around Lake Luo and the western end of the Valley of Dread quite well and it has never seen anything like Omu there before.',
        monsters:true, 
        name: "Cyclops",
        rolls:2,
        die:6,
        extra:0 
        },
    { 
        id: 17,
        title: 'Allosaurus',
        text: 'Theparty scent atteracts 1d4-1 allorsaurus.  Any characters who succeed ona DC 15 Survival check find a safe place to hide, high branch, hole etc, where the "honkers" cant reach them',
        monsters:true, 
        name:'Allosaurus',
        rolls:1,
        die:4,
        extra:-1
            
    } ,
      { id: 18,
        title: 'Ankylosaurus',
        text: 'An ornery Ankylosaurus (club tail dino) is gorging itself on plants and attacks any thing that gets in its way.',
        monsters:true, 
            name: "",
            rolls:1,
            die:0,
            extra:3,
        } ,
      { id: 19,
        title: 'Brontosuarus',
        text: 'A large brontosaurus lumbers towards the characters.  It doesnt notice the party and may step on them but only ifghts back in self defense',
        monsters:true, 
            name: "plsiosaurus",
            rolls:1,
            die:0,
            extra:3,
        } ,
      { id: 20,
        title: 'Deinonychus',
        text: 'A wild boar races bas the party being chased by 1d4+2 deinonychuses the predators decide the characters are more interesting than the prey.',
        monsters:true, 
            name: "Deinonychus",
            rolls:1,
            die:4,
            extra:2,
        } ,
      { id: 21,
        title: 'Deinonychus',
        text: 'A wild boar races bas the party being chased by 1d4+2 deinonychuses the predators decide the characters are more interesting than the prey.',
        monsters:true, 
            name: "Deinonychus",
            rolls:1,
            die:4,
            extra:2,
        } ,
      { id: 22,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters:true, 
        name: "Hadrosaurus",
        rolls:3,
        die:6,
        extra:0,  
     },
      { id: 23,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters:true, 
        name: "Hadrosaurus",
        rolls:3,
        die:6,
        extra:0,
        }, 
      { id: 24,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters:true, 
        name: "Hadrosaurus",
        rolls:3,
        die:6,
        extra:0,
        } ,
      { id: 25,
        title: 'Stegasaurus',
        text: 'This lone stegosaurus is in a genial mood and approaches the characters out of curiosity.  Anyone who touches it triggers a swipe from its tail.',
        monsters:true, 
            name: "Pternadon",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 26,
        title: 'Stegasaurus',
        text: 'This lone stegosaurus is in a genial mood and approaches the characters out of curiosity.  Anyone who touches it triggers a swipe from its tail.',
        monsters:true, 
            name: "Pternadon",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 27,
        title: 'Triceratops',
        text: 'A triceratops who apperas to be grazing alone is actually a mother with a nearby nest containing one noncombatant hatchling and two unhatched eggs.  The mother eyes the characters supiciously but doesnt attack unless they position themselves between her and the nest.  Ifan Talor in Port Nyanzaru offers 50gp for a young triceratops or an intact egg.  Can be talked up to 150 gold on asuccessful Charisma check of 15',
        monsters:true, 
            name: "Triceratops",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 28,
        title: 'Triceratops',
        text: 'A triceratops who apperas to be grazing alone is actually a mother with a nearby nest containing one noncombatant hatchling and two unhatched eggs.  The mother eyes the characters supiciously but doesnt attack unless they position themselves between her and the nest.  Ifan Talor in Port Nyanzaru offers 50gp for a young triceratops or an intact egg.  Can be talked up to 150 gold on asuccessful Charisma check of 15',
        monsters:true, 
            name: "Triceratops",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 29,
        title: 'Tyranosaurus Rex',
        text: 'The characters spot a Tyranosaurus Rex 50 feet away.  On an even roll the dinosaur is locked in combat with a triceratops or stegasaurus, giant ape, a pair of giant constrictor snakes, or a mob of ghouls or zombies.  These mobs will not assist the players in any way directly but may weaken the creature so it can be killed by the players.  The characters can avoid the encounter with all players making a DC 15 stealth check.  If any player is proficient in the stealh skill all checks are made with advantage', 
        monsters:true, 
            name: "Tyranosaurus",
            rolls:1,
            die:10,
            extra:0,
        } ,
      { id: 30,
        title: 'Tyranosaurus Rex',
        text: 'The characters spot a Tyranosaurus Rex 50 feet away.  On an even roll the dinosaur is locked in combat with a triceratops or stegasaurus, giant ape, a pair of giant constrictor snakes, or a mob of ghouls or zombies.  These mobs will not assist the players in any way directly but may weaken the creature so it can be killed by the players.  The characters can avoid the encounter with all players making a DC 15 stealth check.  If any player is proficient in the stealh skill all checks are made with advantage',
        monsters:true, 
            name: "Tyranosaurus",
            rolls:1,
            die:10,
            extra:0,
        } ,
      { id: 31,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters:true, 
            name:"Velociraptor",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 32,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters:true, 
            name:"Velociraptor",
            rolls:3,
            die:6,
            extra:0
        } ,
      { id: 33,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters:true, 
            name:"Velociraptor",
            rolls:3,
            die:6,
            extra:0
        } ,
      { id: 34,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters:true, 
            name:"Velociraptor",
            rolls:3,
            die:6,
            extra:0
        } ,
      { id: 35,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters:true, 
            name:"Velociraptor",
            rolls:3,
            die:6,
            extra:0
        } ,
      { id: 36,
        title: 'Dragon, Faerie',
        text: 'An invisible green faerie dragon takes interest in the players and follows them for a while.  If the party is in good spirits the dragon plays cute pranks on them while they camp or travel.  If the party is not upset at these tricks, the dragon reveals itself and answers three questions truthfully.  The dragon recently visited Omu, knows of the -Snake People- who occupy the place.  It also knows things about other landmarks or locations as you determine',
        monsters:true, 
            name:"Faerie Dragon",
            rolls:0,
            die:0,
            extra:0,
        } ,
      { id: 37,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters:true, 
            name:"Eblis",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 38,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.'  + 
        "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check."  +
        "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters:true, 
            name: "Scout",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 39,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.'  + 
        "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check."  +
        "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters:true, 
            name: "Scout",
            rolls:1,
            die:4,
            extra:1,
        } ,
      {id: 40,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.'  + 
        "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check."  +
        "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters:true, 
            name: "Scout",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 41,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.'  + 
        "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check."  +
        "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters:true, 
            name: "Scout",
            rolls:1,
            die:4,
            extra:1,
         },
      { id: 42,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.'  + 
        "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check."  +
        "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters:true, 
            name: "Scout",
            rolls:1,
            die:4,
            extra:1,
         },
      { id: 43,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.' ,
        monsters:true, 
            name:"Dead Adventurers",
            rolls:1,
            die:6,
            extra:0
        } ,
      { id: 44,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.',
        monsters:true, 
            name:"Dead Adventurers",
            rolls:1,
            die:6,
            extra:0
        } ,
      { id: 45,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters:true, 
            name:"Tribal Warrior",
            rolls:1,
            die:6,
            extra:0
        } ,
      { id: 46,
        title: 'Flail Snail',
        text: 'The characters come across the slimy trail of a Flail Snail.  A DC 10 survival check succesfully tacks the snail.',
        monsters:true, 
            name:"Flail Snail",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 47,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters:true, 
            name:"guard",
            rolls:2,
            die:6,
            extra:0
        } ,
      { id: 48,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters:true, 
            name:"guard",
            rolls:2,
            die:6,
            extra:0
        } ,
      { id: 49,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters:true, 
            name:"guard",
            rolls:2,
            die:6,
            extra:0
        } ,
      { id: 49,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters:true, 
            name:"guard",
            rolls:2,
            die:6,
            extra:0,

         },
      { id: 51,
        title: 'Fyling Monkeys',
        text: 'The sound of flapping wings heralds the arrival of 3d6 flying monkies which swoop through the adventurers in a wave of grasping hands and feet.  Each character must make a dc 12 dex save or lose a useful peice of gear.',
        monsters:true, 
            name:"Flying Monkey",
            rolls:3,
            die:6,
            extra:0,

         },
      { id: 53,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters:true, 
            name:"Flying Snake",
            rolls:2,
            die:6,
            extra:0,
         },
      { id: 53,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters:true, 
            name:"Flying Snake",
            rolls:2,
            die:6,
            extra:0,
        } ,
      {id: 54,
        title: 'Frost Giants',
        text: 'Thecharacters hear the sound of huge creatures stomping through the wilderness.  If they follow the noise they encounter a party of 3 frost giants searching the jungle accompanied by 1d4-2 winter wolves.  Roll a d10, on 9 or 10 this is Drufis search party (page 64 TOA book).  The frost giants are looking for Artus Climber and the ring of winter and they may help characters who provide useful information.  They immediately attack anyone who witholds information or who threaten to reveal their location to the flaming fist.  They carry no treasure',
        monsters:true, 
            name: "Frost Giant",
            rolls:0,
            die:0,
            extra:3
        } ,
      { id: 55,
        title: 'Frost Giants',
        text: 'Thecharacters hear the sound of huge creatures stomping through the wilderness.  If they follow the noise they encounter a party of 3 frost giants searching the jungle accompanied by 1d4-2 winter wolves.  Roll a d10, on 9 or 10 this is Drufis search party (page 64 TOA book).  The frost giants are looking for Artus Climber and the ring of winter and they may help characters who provide useful information.  They immediately attack anyone who witholds information or who threaten to reveal their location to the flaming fist.  They carry no treasure',
        monsters:true, 
            name: "Frost Giant",
            rolls:0,
            die:0,
            extra:3
        } ,
      { id: 56,
        title: 'Giant Boars',
        text: 'The party comes upon 1d4+1 giant boards foraging ahead.  SKirting aruond the boars to prevent an attack requires a DC 12 group Stealth check',
        monsters:true, 
            name: "Giant Boar",
            rolls:1,
            die:4,
            extra:1
        } ,
      { id: 57,
        title: 'Giant Frogs',
        text: 'These 2d6 giant frogs have come together in bunger and tro to eat eeverything that crosses their path.  The characters have plenty of warning nas the amphibians hop noisly towards them',
        monsters:true, 
            name: "Giant Frog",
            rolls:2,
            die:6,
            extra:3
        } ,
      { id: 58,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters:true, 
            name: "Giant Lizard",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 59,
        title: 'Giant Scorpions',
        text: 'Any character with a passive perception above 11 notices 1d4-1 giant scorpions as they emerge from the underbrush and attack.  At the end of the encounter, any character damaged by the creatures must suceed on a DC 11 Con save or contract "Shivering Sickness" ',
        monsters:true, 
            name: "Giant Scorpions",
            rolls:1,
            die:4,
            extra:-1,
        } ,
      { id: 60,
        title: 'Giant Wasps',
        text: 'A droning sound announces the pressence of 1d6 Giant Wasps before the characters see them.  The Wasps all attack at once ignoring those with heavy armor in favor of those with limited or no armor.  Any character damaged by the wasps must make a DC 11 con save at the end of combat of contract Shivering Sickness',
        monsters:true, 
            name: "Giant Wasp",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 61,
        title: 'Girralons',
        text: 'Two Girallons (four-armed super gorillas) are spotted in the trees or lumnber between crumbling, vine-covered ruins.  The group can skirt past ona  DC 13 group stealth check. If the characters defeat, ro frighten the gorillons away a search of the area finds a hidden cache, roll on the cache table.  Also roll once on the treasure table to determine what the gorillans have stashed',
        monsters:true, 
            name: "Girralon",
            rolls:1,
            die:0,
            extra:2,
        } ,
      { id: 62,
        title: 'Girralons',
        text: 'Two Girallons (four-armed super gorillas) are spotted in the trees or lumnber between crumbling, vine-covered ruins.  The group can skirt past ona  DC 13 group stealth check. If the characters defeat, ro frighten the gorillons away a search of the area finds a hidden cache, roll on the cache table.  Also roll once on the treasure table to determine what the gorillans have stashed',
        monsters:true, 
            name: "Girralon",
            rolls:1,
            die:0,
            extra:2,
        } ,
      { id: 63,
        title: 'Goblins',
        text: 'A Batari patrol of a goblin boss + 2d6+2 golbins all wearing painted wooden masks.  NIGHT: any player on watch must suceed on a dc 16 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised.  DAY:  Each player must make a DC 16 insight check to spot the signs of an ambush and an eerie silence in the jungle.  Othersiwse they are surprised.  Goblins will baragain for their lives and can be coerced or forced to serve as a guide with +1 survival.',
        monsters:true, 
            name: "Goblin",
            rolls:2,
            die:6,
            extra:2,
        } ,
        { id: 63,
            title: 'Goblins',
            text: 'A Batari patrol of a goblin boss + 2d6+2 golbins all wearing painted wooden masks.  NIGHT: any player on watch must suceed on a dc 16 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised.  DAY:  Each player must make a DC 16 insight check to spot the signs of an ambush and an eerie silence in the jungle.  Othersiwse they are surprised.  Goblins will baragain for their lives and can be coerced or forced to serve as a guide with +1 survival.',
            monsters:true, 
                name: "Goblin",
                rolls:2,
                die:6,
                extra:2,
            }  ,
      { id: 65,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters:true, 
            name: "Grung",
            rolls:2,
            die:6,
            extra:1,
        } ,
      { id: 66,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters:true, 
            name: "Grung",
            rolls:2,
            die:6,
            extra:1,
        } ,
      { id: 67,
        title: 'Jaculis',
        text: 'Without warning, 1d6 Jaculis (javelin like, dragon faced snakes) leap from the jungle and attack.  Any character with a passive perception of 14 or higher is not suprised. ',
        monsters:true, 
            name: "Jaculi",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 68,
        title: 'Kamadans',
        text: 'The party is ambushed by 1d4-2 Kamadans( leopards with snakes growing out of them).  Any player with a passive perceptions of 16 or higher are not surpised.  A DC 15 search of the area finds a Kamadan lair.  roll a d4 , ona  4 the lair contains 1d4-1 noncombatant kamadan cubs the size of housecats.  They can be sold in Port Nyanzaru for 150 gold or 300 gol on a dc 15 charisma check.',
        monsters:true, 
            name:"Kamadan",
            rolls:2,
            die:4,
            extra:0,
        } ,
      { id: 69,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters:true, 
            name:"Lizardfolk",
            rolls:2,
            die:4,
            extra:0,
        } ,
      { id: 70,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters:true, 
            name:"Lizardfolk",
            rolls:2,
            die:4,
            extra:0,
        } ,
      { id: 71,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters:true, 
            name:"Mad Monkey Mist",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 72,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters:true, 
            name:"Mad Monkey Mist",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 73,
        title: 'Mantraps',
        text: 'The characters wander into a patch of 1d4+1 mantraps (giant man eating plant). The plants are indistinguishable until they attack.  The plants are spaced 10 ft apart and must wait until players come close enough to attack.',
        monsters:true, 
            name:"Mantrap",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 74,
        title: 'Night Hag',
        text: 'One of the Sewn Sisters (hags from the tomb of anihilation) has been following the party staying in the Border Ethereal.  During the partys next long rest, she materialzies, snatches one of the partys blood or hair and disappears returning to the ethereal plane.',
        monsters:true, 
            name:"Night Hag",
            rolls:1,
            die:0
            ,
            extra:0,
        } ,
      { id: 75,
        title: 'Pterrafolk',
        text: 'Looming in the sky 1d4+2 pterafolk watch the characters every move and wait until they blunder into danger, the next time an encounter occurs, the Pterafolk attack launching javelin attacks and staying out of melee range.  With firm resistance the pterafolk retreat but may regroup to attack at your discretion' ,
        monsters:true, 
            name:"Pterafolk",
            rolls:1,
            die:4,
            extra:2
        } ,
      { id: 76,
        title: 'Rare Plant',
        text: 'The characters find one or more unusall plants determind by a d6 roll.  1  - 2d6 dancing monkey fruit growing on a tree. 2 - manga bush with 2d6 ounces of leaves.  3 - 1d4 ryath roots growing in gorund. 4 4d6 sindaberries growing in a bush.  5 - wukka tree with 2d6 wukka nuts.  6 1d6 zabu growing on a dead tree.',
        monsters:false, 
            name:"",
            rolls:1,
            die:6,
            extra:0
         },
      { id: 77,
        title: 'Red Wizard',
        text: 'This group consists of 1 red wizard, LE, human mage, 1d6 guards, and 1d6 skeletons, all answerable to Velinda Shadowmantle.  If this encounter happens outside of the city of Omu, they are reinforcements on their way to the city.  If inside Omu the party is searching the citry for shrines (chapter 3).  They are not spoiling for a fight and if things look grim, they will surrender and offer up a crudely drawn map of Chult with the location of known undead hordes.',
        monsters:true, 
            name:"Red Wizard",
            rolls:1,
            die:6,
            extra:0,
         },
      { id: 78,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"constrictor snake",
            rolls:0,
            die:0,
            extra:0
         },
      { id: 79,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"constrictor snake",
            rolls:0,
            die:0,
            extra:0
         },
      { id: 80,
        title: 'Snake, Giant Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"Giant Constrictor Snake",
            rolls:2,
            die:6,
            extra:0,
         },
      { id: 81,
        title: 'Snake, Giant Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"Giant Constrictor Snake",
            rolls:2,
            die:6,
            extra:0,
         },
      { id: 82,
        title: 'Spiders',
        text: 'Giant spiderwbs are easily concealed in Chults dense jungles and swamps.  Passive perception of 13 or higher alerts the characeters in time for an encounter with 1d6 giant spiders.  Otherwise, the lead party member stumbles into an ambush and becomes grappled with a escape dc of 12 - the spiders have suprise and 100s of harmless baby spiders crawl through the webs', 
        monsters:true, 
            name:"Giant Spider",
            rolls:1,
            die:6,
            extra:0,
         },
      { id: 83,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters:false, 
            name:"",
            rolls:2,
            die:6,
            extra:0,
         },
      { id: 84,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters:false, 
            name:"",
            rolls:2,
            die:6,
            extra:0,
         },
      { id: 85,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters:false, 
            name:"",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 86,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters:true, 
            name:"Stirge",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 87,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters:true, 
            name:"Stirge",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 88,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters:true, 
            name:"Swarm of Bats",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 89,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters:true, 
            name:"Swarm of Bats",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 90,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters:true, 
            name:"Tabaxi Hunter",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 91,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters:true, 
            name:"Tabaxi Hunter",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 92,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters:true, 
            name:"Tabaxi Hunter",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 93,
          title: 'Vegepygmy',
        text: 'The characters cross path with 1d4 vegepygmys each one mounted on a Thorny.  The hunters have wandered far from their tribe.  They flee if outnumbered otherwise they attack.',
        monsters:true, 
            name:"Vegepygmy",
            rolls:0,
            die:0,
            extra:1,
        },
      { id: 94,
        title: 'Wereboar',
        text: 'A wereboar masquerading as a chultan priest takes a dim view of explorers encroaching on its territory.  On its neck is a wooden labrynth carved into a wooden disk.  The symbol of Ubtao.  He might be guarding a shrine to Ubtao a grove of wukka trees or a cave it uses as a lair.  It may also have treasure.  Roll 3 trasure drops in the trasure table.',
        monsters:true, 
            name:"Wereboar",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 95,
        title: 'Weretiger',
        text: 'In human forma  weretiger offers to excort the party through a very dangerous stretch of wilderness.  If they accompany her, they cannot get attacked.  She will leave after 24 hours and will not go to Omu Nangalore or Orolunga.',
        monsters:true, 
            name:"Weretiger",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 96,
        title: 'Winterscape',
        text: 'The characters stumble intoa  112 ft radius sphere of winter weather.  Artus used the ring of winter to drive off monsters.  All plants are covered in glittering ice and frost.  The temperature in here is a biting -30 degrees farenhiet and cannot be dispelled.',
        monsters:false, 
            name:"",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 97,
        title: 'Yellow musk creeper and zombies',
        text: 'The characters pass close to a ruin inhabited by 3d6 Yellow Musk Zombies.  Somewhere within the ruin a Yellow Musk Creeper clings to a wall.  If this encounter occurs while the players are camped the zombies attack the camp and attempt to drag the party back to the ruin',
        monsters:true, 
            name:"Yellow Musk Creeper",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 98,
        title: 'Yuan-ti',
        text: 'Yuan-ti patrols consist of 1d6+1 Yuan-ti purebloods who keep their distance while they try to gather information to bring back to Ras Nsi.  The Yuan-ti are disguised but any character who succeeds on a DC 13 Perception check made with disadvantage catches sight of the serpent folk as they withdraw. If within 25 miles of OMU the group is 1d4+1 yuan-ti Malisons instead and the check is DC 14',
        monsters:true, 
            name:"Yuan-ti",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 99,
        title: 'Zhentarim',
        text: 'A zhent assassin with a fling snake pet leads a priest, 2d6 thugs and 1d6 tribal warriors through the wilderness in search of Artus Cimber and The Ring of Winter.  If Artus is with the party the Zhents attack to get the ring otherwise they show little interest.  Roll on the treasure table to determine what if anything they carry',
        monsters:true, 
            name:"Assassin",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 100,
        title: 'Zorbos',
        text: 'If his encounter happens in the wild the party stumbled upon 2d6 Zorbos in wukka trees who attack if the party makes threatening motions.  If during camp, the Zorbos drop from surrounding trees and attack.',
        monsters:true, 
            name:"Zorbo",
            rolls:2,
            die:6,
            extra:0,
        },
    ]





