import { Event } from './event';
import { Component, OnInit } from '@angular/core';
export const riverEvents: Event[] = [
    {
        id: 1,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,

    },
    {
        id: 2,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 3,
        title: 'Aarakocra',
        text: "Any character with a passive Widsom (perception) score of 15 or higher spots 1d4+1 aarakocra flying overhead.  These creatures are scouts from Kir Sabal or another aeire.  They observe the party from a safe distance but dont approach unless the characters demonstrate peaceful intentions.  The bird folk are friendly and can point characrers in the direction of nearby landmarks.",
        monsters: true,
        name: "Aarakocra",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 4,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 5,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 6,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 7,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 8,
        title: 'Artus Climber',
        text: "Artus CLimber with or without his saurial traveling companion DragonBait, can be encounterd almost anywhere.  He may use the ring of winter to save the characters.  He is friendly  ",
        monsters: true,
        name: "Artus Climber",
        rolls: 1,
        die: 1,
        extra: 0,


    },
    {
        id: 9,
        title: 'Artus Climber',
        text: "Artus CLimber with or without his saurial traveling companion DragonBait, can be encounterd almost anywhere.  He may use the ring of winter to save the characters.  He is friendly  ",
        monsters: true,
        name: "Artus Climber",
        rolls: 1,
        die: 1,
        extra: 0,


    },
    {
        id: 10,
        title: 'Assassin Vine',
        text: "The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters: true,
        name: "Assassin Vine",
        rolls: 2,
        die: 4,
        extra: -1,
    },
    {
        id: 11,
        title: 'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters: false,
        name: "",
        rolls: 0,
        die: 0,
        extra: 0,
    },
    {
        id: 12,
        title: 'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters: false,
        name: "",
        rolls: 0,
        die: 0,
        extra: 0,
    },
    {
        id: 13,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters: true,
        name: 'Tribal Warrior',
        rolls: 3,
        die: 6,
        extra: 0

    },
    {
        id: 14,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters: true,
        name: 'Tribal Warrior',
        rolls: 3,
        die: 6,
        extra: 0

    },
    {
        id: 15,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters: true,
        name: 'Tribal Warrior',
        rolls: 3,
        die: 6,
        extra: 0

    },
    {
        id: 16,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters: true,
        name: 'Tribal Warrior',
        rolls: 3,
        die: 6,
        extra: 0

    },
    {
        id: 17,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 18,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 19,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 20,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 21,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 22,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 23,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 24,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 25,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 26,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 27,
        title: 'Brontosuarus',
        text: 'A large brontosaurus lumbers towards the characters.  It doesnt notice the party and may step on them but only ifghts back in self defense',
        monsters: true,
        name: "Brontosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 28,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 29,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 30,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters: true,
        name: "Hadrosaurus",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 28,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters: true,
        name: "Hadrosaurus",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 29,
        title: 'Plesiosuarus',
        text: 'Two plesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 30,
        title: 'Plesiosuarus',
        text: 'Two plesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 31,
        title: 'Plesiosuarus',
        text: 'Two plesiosaurus are fighting over a dead giant octopus.  If the characters are on a river the creatures are spotted at a distance of 300 ft.  To paddle to safety, one character must succeed ona DC 13 Athletics check.  Other characters in the canoe mayu use the Help action to assist.  Canoes that dont reach the shore are flipped and destroyed by the dinosaurs who then attack.',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 32,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 33,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 34,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 35,
        title: 'Quetzalcoatlus',
        text: 'A fight of 1d4 Quetzalcoatlus are spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Quetzalcoatlus ",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 36,
        title: 'Quetzalcoatlus',
        text: 'A fight of 1d4 Quetzalcoatlus are spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Quetzalcoatlus ",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 37,
        title: 'Dragon, Faerie',
        text: 'An invisible green faerie dragon takes interest in the players and follows them for a while.  If the party is in good spirits the dragon plays cute pranks on them while they camp or travel.  If the party is not upset at these tricks, the dragon reveals itself and answers three questions truthfully.  The dragon recently visited Omu, knows of the -Snake People- who occupy the place.  It also knows things about other landmarks or locations as you determine',
        monsters: true,
        name: "Faerie Dragon",
        rolls: 0,
        die: 0,
        extra: 0,
    },
    {
        id: 38,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters: true,
        name: "Eblis",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 39,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters: true,
        name: "Eblis",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 40,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters: true,
        name: "Eblis",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 41,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.' +
            "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check." +
            "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters: true,
        name: "Scout",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 42,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.' +
            "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check." +
            "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters: true,
        name: "Scout",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 43,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.' +
            "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check." +
            "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters: true,
        name: "Scout",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 44,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.',
        monsters: true,
        name: "Dead Adventurers",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 45,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.',
        monsters: true,
        name: "Dead Adventurers",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 46,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 47,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 48,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 49,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 50,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters: true,
        name: "guard",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 51,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters: true,
        name: "guard",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 52,
        title: 'Fyling Monkeys',
        text: 'The sound of flapping wings heralds the arrival of 3d6 flying monkies which swoop through the adventurers in a wave of grasping hands and feet.  Each character must make a dc 12 dex save or lose a useful peice of gear.',
        monsters: true,
        name: "Flying Monkey",
        rolls: 3,
        die: 6,
        extra: 0,

    },
    {
        id: 53,
        title: 'Fyling Monkeys',
        text: 'The sound of flapping wings heralds the arrival of 3d6 flying monkies which swoop through the adventurers in a wave of grasping hands and feet.  Each character must make a dc 12 dex save or lose a useful peice of gear.',
        monsters: true,
        name: "Flying Monkey",
        rolls: 3,
        die: 6,
        extra: 0,

    },
    {
        id: 54,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 55,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 56,
        title: 'Giant Crocodile',
        text: 'Before it rises out of the water the giant crocodile makes a stealth check vs players passive perception.  Any player lower than the stealth is surprised. ',
        monsters: true,
        name: "Giant Crocodile",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 57,
        title: 'Giant Crocodile',
        text: 'Before it rises out of the water the giant crocodile makes a stealth check vs players passive perception.  Any player lower than the stealth is surprised. ',
        monsters: true,
        name: "Giant Crocodile",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 58,
        title: 'Giant Crocodile',
        text: 'Before it rises out of the water the giant crocodile makes a stealth check vs players passive perception.  Any player lower than the stealth is surprised. ',
        monsters: true,
        name: "Giant Crocodile",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 59,
        title: 'Giant Frogs',
        text: 'These 2d6 giant frogs have come together in bunger and tro to eat eeverything that crosses their path.  The characters have plenty of warning nas the amphibians hop noisly towards them',
        monsters: true,
        name: "Giant Frog",
        rolls: 2,
        die: 6,
        extra: 3
    },
    {
        id: 60,
        title: 'Giant Frogs',
        text: 'These 2d6 giant frogs have come together in bunger and tro to eat eeverything that crosses their path.  The characters have plenty of warning nas the amphibians hop noisly towards them',
        monsters: true,
        name: "Giant Frog",
        rolls: 2,
        die: 6,
        extra: 3
    },
    {
        id: 61,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 62,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 63,
        title: 'Giant Wasps',
        text: 'A droning sound announces the pressence of 1d6 Giant Wasps before the characters see them.  The Wasps all attack at once ignoring those with heavy armor in favor of those with limited or no armor.  Any character damaged by the wasps must make a DC 11 con save at the end of combat of contract Shivering Sickness',
        monsters: true,
        name: "Giant Wasp",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 64,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters: true,
        name: "Grung",
        rolls: 2,
        die: 6,
        extra: 1,
    },
    {
        id: 65,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters: true,
        name: "Grung",
        rolls: 2,
        die: 6,
        extra: 1,
    },
    {
        id: 66,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters: true,
        name: "Grung",
        rolls: 2,
        die: 6,
        extra: 1,
    },
    {
        id: 67,
        title: 'Jaculis',
        text: 'Without warning, 1d6 Jaculis (javelin like, dragon faced snakes) leap from the jungle and attack.  Any character with a passive perception of 14 or higher is not suprised. ',
        monsters: true,
        name: "Jaculi",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 68,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters: true,
        name: "Lizardfolk",
        rolls: 2,
        die: 4,
        extra: 0,
    },
    {
        id: 69,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters: true,
        name: "Mad Monkey Mist",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 70,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters: true,
        name: "Mad Monkey Mist",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 71,
        title: 'Pterrafolk',
        text: 'Looming in the sky 1d4+2 pterafolk watch the characters every move and wait until they blunder into danger, the next time an encounter occurs, the Pterafolk attack launching javelin attacks and staying out of melee range.  With firm resistance the pterafolk retreat but may regroup to attack at your discretion',
        monsters: true,
        name: "Pterafolk",
        rolls: 1,
        die: 4,
        extra: 2
    },
    {
        id: 72,
        title: 'Pterrafolk',
        text: 'Looming in the sky 1d4+2 pterafolk watch the characters every move and wait until they blunder into danger, the next time an encounter occurs, the Pterafolk attack launching javelin attacks and staying out of melee range.  With firm resistance the pterafolk retreat but may regroup to attack at your discretion',
        monsters: true,
        name: "Pterafolk",
        rolls: 1,
        die: 4,
        extra: 2
    },
    {
        id: 73,
        title: 'Rare Plant',
        text: 'The characters find one or more unusall plants determind by a d6 roll.  1  - 2d6 dancing monkey fruit growing on a tree. 2 - manga bush with 2d6 ounces of leaves.  3 - 1d4 ryath roots growing in gorund. 4 4d6 sindaberries growing in a bush.  5 - wukka tree with 2d6 wukka nuts.  6 1d6 zabu growing on a dead tree.',
        monsters: false,
        name: "",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 74,
        title: 'Red Wizard',
        text: 'This group consists of 1 red wizard, LE, human mage, 1d6 guards, and 1d6 skeletons, all answerable to Velinda Shadowmantle.  If this encounter happens outside of the city of Omu, they are reinforcements on their way to the city.  If inside Omu the party is searching the citry for shrines (chapter 3).  They are not spoiling for a fight and if things look grim, they will surrender and offer up a crudely drawn map of Chult with the location of known undead hordes.',
        monsters: true,
        name: "Red Wizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 75,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 76,
        title: 'Sea Hag',
        text: 'Thecharacters encounter 3 sea hags that compromise a coven.  They lure the party into the water by pretending to be drowning humans.  If the characters defeat the sea hags and search the area roll three times on the Treasure Table',
        monsters: true,
        name: "Sea Hag",
        rolls: 0,
        die: 0,
        extra: 3,
    },
    {
        id: 80,
        title: 'Snake, Giant Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters: true,
        name: "Giant Constrictor Snake",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 81,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters: false,
        name: "",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 82,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters: true,
        name: "Stirge",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 83,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters: true,
        name: "Stirge",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 84,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters: true,
        name: "Swarm of Insects",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 85,
        title: 'Swarm Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters: true,
        name: "Swarm Quippers",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 86,
        title: 'Swarm Quippers',
        text: '1d6 quippers in the water',
        monsters: true,
        name: "Swarm Quippers",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 87,
        title: 'Swarm Quippers',
        text: '1d6 quippers in the water',
        monsters: true,
        name: "Swarm Quippers",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 88,
        title: 'Swarm Quippers',
        text: '1d6 quippers in the water',
        monsters: true,
        name: "Swarm Quippers",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 89,
        title: 'Swarm Quippers',
        text: '1d6 quippers in the water',
        monsters: true,
        name: "Swarm Quippers",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 90,
        title: 'Swarm Quippers',
        text: '1d6 quippers in the water',
        monsters: true,
        name: "Swarm Quippers",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 91,
        title: 'Swarm Quippers',
        text: '1d6 quippers in the water',
        monsters: true,
        name: "Swarm Quippers",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 92,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters: true,
        name: "Tabaxi Hunter",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 93,
        title: 'Tabaxi Hunter',
        text: 'Anyplayer with a passive perception score higher than 15 notices a Tabaxi Hunter from a vantage point 300 ft away. If the hunter remains unseen it may follow the characters for a while, assisting them in a tough encounter.  If this encounter takes palce in Omu, see chapter 3 for information on the Tabaxi encountered there.',
        monsters: true,
        name: "Tabaxi Hunter",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 94,
        title: 'Ghouls',
        text: 'Any passive perception 12 or hihger hears and smells a ghoul pack approaching consisting of 2d6 ghouls led by a ghast.  The Ghast has a blue triangle tattooed on its forehead indicator that it once served ras nsi.',
        monsters: true,
        name: "Ghoul",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 95,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters: true,
        name: "Skeleton",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 96,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters: true,
        name: "Zombie",
        rolls: 1,
        die: 10,
        extra: 3,
    },
    {
        id: 97,
        title: 'Yuan-ti',
        text: 'Yuan-ti patrols consist of 1d6+1 Yuan-ti purebloods who keep their distance while they try to gather information to bring back to Ras Nsi.  The Yuan-ti are disguised but any character who succeeds on a DC 13 Perception check made with disadvantage catches sight of the serpent folk as they withdraw. If within 25 miles of OMU the group is 1d4+1 yuan-ti Malisons instead and the check is DC 14',
        monsters: true,
        name: "Yuan-ti",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 98,
        title: 'Yuan-ti',
        text: 'Yuan-ti patrols consist of 1d6+1 Yuan-ti purebloods who keep their distance while they try to gather information to bring back to Ras Nsi.  The Yuan-ti are disguised but any character who succeeds on a DC 13 Perception check made with disadvantage catches sight of the serpent folk as they withdraw. If within 25 miles of OMU the group is 1d4+1 yuan-ti Malisons instead and the check is DC 14',
        monsters: true,
        name: "Yuan-ti",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 99,
        title: 'Zhentarim',
        text: 'A zhent assassin with a fling snake pet leads a priest, 2d6 thugs and 1d6 tribal warriors through the wilderness in search of Artus Cimber and The Ring of Winter.  If Artus is with the party the Zhents attack to get the ring otherwise they show little interest.  Roll on the treasure table to determine what if anything they carry',
        monsters: true,
        name: "Assassin",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 100,
        title: 'Zhentarim',
        text: 'A zhent assassin with a fling snake pet leads a priest, 2d6 thugs and 1d6 tribal warriors through the wilderness in search of Artus Cimber and The Ring of Winter.  If Artus is with the party the Zhents attack to get the ring otherwise they show little interest.  Roll on the treasure table to determine what if anything they carry',
        monsters: true,
        name: "Assassin",
        rolls: 3,
        die: 6,
        extra: 0,
    },














]