import { Event } from './event';
import { Component, OnInit } from '@angular/core';
export const swampEvents: Event[] = [
    {
        id: 1,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,

    },
    {
        id: 2,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 3,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 4,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 5,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 6,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 7,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 8,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,


    },
    {
        id: 9,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,


    },
    {
        id: 10,
        title: 'Aldani',
        text: "The characters are shadowed by 1d4 aldani which are noticed by a passive perception of 13.  The Aldani don't communicate and wont fight unless the characters refuse to take a bribe to leave the area.  They will aid the characters only if offered something of great value in return",
        monsters: true,
        name: "Aldani",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 11,
        title: 'Artus Climber',
        text: "Artus CLimber with or without his saurial traveling companion DragonBait, can be encounterd almost anywhere.  He may use the ring of winter to save the characters.  He is friendly  ",
        monsters: true,
        name: "Artus Climber",
        rolls: 1,
        die: 1,
        extra: 0,
    },
    {
        id: 12,
        title: 'Assassin Vine',
        text: "The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters: true,
        name: "Assassin Vine",
        rolls: 2,
        die: 4,
        extra: -1,
    },
    {
        id: 13,
        title: 'Assassin Vine',
        text: "The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters: true,
        name: "Assassin Vine",
        rolls: 2,
        die: 4,
        extra: -1,

    },
    {
        id: 14,
        title: 'Assassin Vine',
        text: "The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters: true,
        name: "Assassin Vine",
        rolls: 2,
        die: 4,
        extra: -1,

    },
    {
        id: 15,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters: true,
        name: 'Tribal Warrior',
        rolls: 3,
        die: 6,
        extra: 0

    },
    {
        id: 16,
        title: 'Chwinga',
        text: 'A chwinga takes an interest in the characters. It attempts to steal something valuable from an ungauarded pack or canoe but is noticed by any character witha  passive perceptin score of 17 or higher.  The chwinga always leaves something in return, a pretty shell, some twigs, or an uncut gemstone (10gold)',
        monsters: true,
        name: 'Chwinga',
        rolls: 1,
        die: 1,
        extra: 0

    },
    {
        id: 17,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 18,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 19,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 20,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 21,
        title: 'Crocodiles',
        text: 'Any passive perception over 14 notices 1d4 crocodiles coming towards the party.  All other characters are surprised.  The corcodiles can capsize a canoe with a successful dc 15 strength check',
        monsters: true,
        name: 'Crocodile',
        rolls: 1,
        die: 4,
        extra: 0
    },
    {
        id: 22,
        title: 'Allosaurus',
        text: 'Theparty scent atteracts 1d4-1 allorsaurus.  Any characters who succeed ona DC 15 Survival check find a safe place to hide, high branch, hole etc, where the "honkers" cant reach them',
        monsters: true,
        name: 'Allosaurus',
        rolls: 1,
        die: 4,
        extra: -1
    },
    {
        id: 23,
        title: 'Ankylosaurus',
        text: 'An ornery Ankylosaurus (club tail dino) is gorging itself on plants and attacks any thing that gets in its way.',
        monsters: true,
        name: "",
        rolls: 1,
        die: 0,
        extra: 3
    },
    {
        id: 24,
        title: 'Brontosuarus',
        text: 'A large brontosaurus lumbers towards the characters.  It doesnt notice the party and may step on them but only ifghts back in self defense',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 25,
        title: 'Brontosuarus',
        text: 'A large brontosaurus lumbers towards the characters.  It doesnt notice the party and may step on them but only ifghts back in self defense',
        monsters: true,
        name: "plsiosaurus",
        rolls: 1,
        die: 0,
        extra: 3,
    },
    {
        id: 26,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 27,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 28,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 29,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 30,
        title: 'Dimetrodon',
        text: 'a pack of 2d6 dimetrodon are spotted on a sunny riverbank or on rocks along the water.  Roll any die.  on an odd number the dinosuars attack the party if they come within 100 feet.  Otherwise they pay them no notice',
        monsters: true,
        name: "Dimetrodon",
        rolls: 2,
        die: 6,
        extra: 0
    },
    {
        id: 31,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters: true,
        name: "Hadrosaurus",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 32,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters: true,
        name: "Hadrosaurus",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 33,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters: true,
        name: "Hadrosaurus",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 34,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 35,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters: true,
        name: "Pternadon",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 36,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters: true,
        name: "Eblis",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 37,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters: true,
        name: "Eblis",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 38,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters: true,
        name: "Eblis",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 39,
        title: 'Eblis',
        text: 'If the party is on the move while this encounter takes place they stumble upone 1d4+1 eblis (evil, reincarnated people as ostritches) living in reed huts built on stilts abouve the swamp, marsh, or pond.  The Eblis will attack any weak looking, or sick characters but offer to trade precious gemstones or information if faced with a well armed, healthy group.  For 50 gold they point the party in direction of a nearby landmark.  If the characters defeat the Eblis and search the huts roll once on the Treasure table.  If this encounter occurs while the party is camped, the Eblis sneak into the camp at night and attack.',
        monsters: true,
        name: "Eblis",
        rolls: 1,
        die: 4,
        extra: 1,
    },
    {
        id: 40,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.',
        monsters: true,
        name: "Dead Adventurers",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 41,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.',
        monsters: true,
        name: "Dead Adventurers",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 42,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 43,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 44,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 45,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters: true,
        name: "Tribal Warrior",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 46,
        title: 'Flail Snail',
        text: 'The characters come across the slimy trail of a Flail Snail.  A DC 10 survival check succesfully tacks the snail.',
        monsters: true,
        name: "Flail Snail",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 47,
        title: 'Flail Snail',
        text: 'The characters come across the slimy trail of a Flail Snail.  A DC 10 survival check succesfully tacks the snail.',
        monsters: true,
        name: "Flail Snail",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 48,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 49,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 50,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters: true,
        name: "Flying Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 51,
        title: 'Giant Crocodile',
        text: 'Before it rises out of the water the giant crocodile makes a stealth check vs players passive perception.  Any player lower than the stealth is surprised. ',
        monsters: true,
        name: "Giant Crocodile",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 52,
        title: 'Giant Crocodile',
        text: 'Before it rises out of the water the giant crocodile makes a stealth check vs players passive perception.  Any player lower than the stealth is surprised. ',
        monsters: true,
        name: "Giant Crocodile",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 53,
        title: 'Giant Crocodile',
        text: 'Before it rises out of the water the giant crocodile makes a stealth check vs players passive perception.  Any player lower than the stealth is surprised. ',
        monsters: true,
        name: "Giant Crocodile",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 54,
        title: 'Giant Frogs',
        text: 'These 2d6 giant frogs have come together in bunger and tro to eat eeverything that crosses their path.  The characters have plenty of warning nas the amphibians hop noisly towards them',
        monsters: true,
        name: "Giant Frog",
        rolls: 2,
        die: 6,
        extra: 3
    },
    {
        id: 55,
        title: 'Giant Frogs',
        text: 'These 2d6 giant frogs have come together in bunger and tro to eat eeverything that crosses their path.  The characters have plenty of warning nas the amphibians hop noisly towards them',
        monsters: true,
        name: "Giant Frog",
        rolls: 2,
        die: 6,
        extra: 3

    },
    {
        id: 56,
        title: 'Giant Frogs',
        text: 'These 2d6 giant frogs have come together in bunger and tro to eat eeverything that crosses their path.  The characters have plenty of warning nas the amphibians hop noisly towards them',
        monsters: true,
        name: "Giant Frog",
        rolls: 2,
        die: 6,
        extra: 3

    },
    {
        id: 57,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 58,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters: true,
        name: "Giant Lizard",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 59,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 60,
        title: 'Giant Snapping Turtle',
        text: 'Theplayers spot a giant snapping turtle sunning itself near the water.  It attacks any player that comes within 30ft',
        monsters: true,
        name: "Giant Snapping Turtle",
        rolls: 0,
        die: 0,
        extra: 1,
    },
    {
        id: 61,
        title: 'Giant Crocodile',
        text: 'Before it rises out of the water the giant crocodile makes a stealth check vs players passive perception.  Any player lower than the stealth is surprised. ',
        monsters: true,
        name: "Giant Crocodile",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 62,
        title: 'Giant Wasps',
        text: 'A droning sound announces the pressence of 1d6 Giant Wasps before the characters see them.  The Wasps all attack at once ignoring those with heavy armor in favor of those with limited or no armor.  Any character damaged by the wasps must make a DC 11 con save at the end of combat of contract Shivering Sickness',
        monsters: true,
        name: "Giant Wasp",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 63,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters: true,
        name: "Grung",
        rolls: 2,
        die: 6,
        extra: 1,
    },
    {
        id: 64,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters: true,
        name: "Grung",
        rolls: 2,
        die: 6,
        extra: 1,
    },

    {
        id: 65,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters: true,
        name: "Lizardfolk",
        rolls: 2,
        die: 4,
        extra: 0,
    },
    {
        id: 66,
        title: 'Lizardfolk',
        text: 'Thecharacters encounter 2d4 lizardfolk and one lizardfolk shaman.  They belong to a nearby tribe in the Valley of Dread and can be appeased with food - 1 days supply of food per lizardfolk, otherwise they attack',
        monsters: true,
        name: "Lizardfolk",
        rolls: 2,
        die: 4,
        extra: 0,
    },
    {
        id: 67,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters: true,
        name: "Mad Monkey Mist",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 68,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters: true,
        name: "Mad Monkey Mist",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 69,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters: true,
        name: "Mad Monkey Mist",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 70,
        title: 'Mephits',
        text: 'The characters might encounter magma mephits, mud mephits, smoke mephits or steam mephits each appearing as a group of 2d6.  The mephits dont attack unless they outnumber the party 2 to 1.  They are reluctant to help unless they are outnumbered',
        monsters: true,
        name: "Mephits",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 71,
        title: 'Night Hag',
        text: 'One of the Sewn Sisters shadows the party while staying in the border ethereal during the parties next long rest the night hag materializes and snatches some blood or hair before returning to the ethereal plane.',
        monsters: true,
        name: "Night Hag",
        rolls: 1,
        die: 6,
        extra: 0,
    },
    {
        id: 72,
        title: 'Rare Plant',
        text: 'The characters find one or more unusall plants determind by a d6 roll.  1  - 2d6 dancing monkey fruit growing on a tree. 2 - manga bush with 2d6 ounces of leaves.  3 - 1d4 ryath roots growing in gorund. 4 4d6 sindaberries growing in a bush.  5 - wukka tree with 2d6 wukka nuts.  6 1d6 zabu growing on a dead tree.',
        monsters: false,
        name: "",
        rolls: 1,
        die: 6,
        extra: 0
    },
    {
        id: 73,
        title: 'Shambling Mound',
        text: 'Roll any die whena  shambling mound encounter occurs.  Even, the characters hear the mound rumbling through the jungle.  Odd, it lies in wait to ambush with a perception of 15 required to spot it',
        monsters: true,
        name: "Shambling Mound",
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 74,
        title: 'Shambling Mound',
        text: 'Roll any die whena  shambling mound encounter occurs.  Even, the characters hear the mound rumbling through the jungle.  Odd, it lies in wait to ambush with a perception of 15 required to spot it',
        monsters: true,
        name: "Shambling Mound",
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 75,
        title: 'Shambling Mound',
        text: 'Roll any die whena  shambling mound encounter occurs.  Even, the characters hear the mound rumbling through the jungle.  Odd, it lies in wait to ambush with a perception of 15 required to spot it',
        monsters: true,
        name: "Shambling Mound",
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 76,
        title: 'Shambling Mound',
        text: 'Roll any die whena  shambling mound encounter occurs.  Even, the characters hear the mound rumbling through the jungle.  Odd, it lies in wait to ambush with a perception of 15 required to spot it',
        monsters: true,
        name: "Shambling Mound",
        rolls: 1,
        die: 1,
        extra: 0
    },
    {
        id: 77,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters: true,
        name: "constrictor snake",
        rolls: 0,
        die: 0,
        extra: 0
    },
    {
        id: 78,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters: true,
        name: "constrictor snake",
        rolls: 0,
        die: 0,
        extra: 0
    },
    {
        id: 79,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters: true,
        name: "constrictor snake",
        rolls: 0,
        die: 0,
        extra: 0
    },
    {
        id: 80,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters: true,
        name: "constrictor snake",
        rolls: 0,
        die: 0,
        extra: 0
    },
    {
        id: 81,
        title: 'Snake, Giant Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters: true,
        name: "Giant Constrictor Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 82,
        title: 'Snake, Giant Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters: true,
        name: "Giant Constrictor Snake",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 83,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters: false,
        name: "",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 84,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters: false,
        name: "",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 85,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters: false,
        name: "",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 86,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters: true,
        name: "Stirge",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 87,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters: true,
        name: "Stirge",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 88,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters: true,
        name: "Swarm of Bats",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 89,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters: true,
        name: "Swarm of Bats",
        rolls: 1,
        die: 4,
        extra: 0,
    },
    {
        id: 90,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters: true,
        name: "Swarm of Insects",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 91,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters: true,
        name: "Swarm of Insects",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 92,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters: true,
        name: "Swarm of Insects",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 93,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters: true,
        name: "Swarm of Insects",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 94,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters: true,
        name: "Swarm of Insects",
        rolls: 2,
        die: 6,
        extra: 2,
    },
    {
        id: 95,
        title: 'Ghouls',
        text: 'Any passive perception 12 or hihger hears and smells a ghoul pack approaching consisting of 2d6 ghouls led by a ghast.  The Ghast has a blue triangle tattooed on its forehead indicator that it once served ras nsi.',
        monsters: true,
        name: "Ghoul",
        rolls: 2,
        die: 6,
        extra: 0,
    },
    {
        id: 96,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters: true,
        name: "Skeleton",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 97,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters: true,
        name: "Skeleton",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 98,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters: true,
        name: "Zombie",
        rolls: 1,
        die: 10,
        extra: 3,
    },
    {
        id: 99,
        title: 'Yellow musk creeper and zombies',
        text: 'The characters pass close to a ruin inhabited by 3d6 Yellow Musk Zombies.  Somewhere within the ruin a Yellow Musk Creeper clings to a wall.  If this encounter occurs while the players are camped the zombies attack the camp and attempt to drag the party back to the ruin',
        monsters: true,
        name: "Yellow Musk Creeper",
        rolls: 3,
        die: 6,
        extra: 0,
    },
    {
        id: 100,
        title: 'Yuan-ti',
        text: 'Yuan-ti patrols consist of 1d6+1 Yuan-ti purebloods who keep their distance while they try to gather information to bring back to Ras Nsi.  The Yuan-ti are disguised but any character who succeeds on a DC 13 Perception check made with disadvantage catches sight of the serpent folk as they withdraw. If within 25 miles of OMU the group is 1d4+1 yuan-ti Malisons instead and the check is DC 14',
        monsters: true,
        name: "Yuan-ti",
        rolls: 1,
        die: 4,
        extra: 0,
    },














]