import { Event } from './event';
import { Component, OnInit } from '@angular/core';


export const undeadEvents: Event[] = [
    {
        id:1,
        title:'Albino Dwarves',
        text:"The characters are ambushed by 1d4+3 Albino Dwarf Warriors that spring forth from a burrow.  Any character with a passive perception above 13 notices the dwarves, everyone else is surprised.  The dwarves prefer to knock out players and steal food, gold, gear rather than kill them.  They break off their attacks if anyone speaks Dwarvish or shows peaceful intentions.",
        monsters:true,
        name: "Albino Dwarf",
        rolls:1,
        die:4,
        extra:3,
        },
        
    
    {
        id:2,
        title:'Artus Cimber',
        text:"Artus Cimber with or without his saurial traveling companion DragonBait, can be encounterd almost anywhere.  He may use the ring of winter to save the characters.  He is friendly  ",
        monsters:true,
        name: "Artus Climber",
        rolls:1,
        die:1,
        extra:0,
    },
    {
        id:3,
        title:'Assassin Vine',
        text:"The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters:true,
        name: "Assassin Vine",
        rolls:2,
        die:4,
        extra:-1,
    },
    {
        id:4,
        title:'Assassin Vine',
        text:"The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters:true,
        name: "Assassin Vine",
        rolls:2,
        die:4,
        extra:-1,
     },
    {
        id:5,
        title:'Assassin Vine',
        text:"The characters come across the path of 1d4-1 assassin vines.  The vines are indistinguishable from normal plants and cannot be spotted by normal perception checks but the plants draw carrion to them so they party may smell dead corpses.  At night the plants may snake their wau into the players camp to drag them away",
        monsters:true,
        name: "Assassin Vine",
        rolls:2,
        die:4,
        extra:-1,
        }
        
    ,
    {
        id:6,
        title:'Axe Beaks',
        text:"A flock of 1d6 +3 Axe Beaks (big ass murder ostritch birds) come crashing through the jungle.  The parrty can hear them before they arrive but can see nothing until the birds are upons them slashing at everything within range. ",
        monsters:true,
        name: "Axe Beak",
        rolls:1,
        die:6,
        extra:3,
        },
    {
        id:7,
        title:'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters:false,
        name:"",
        rolls:0,
        die:0,
        extra:0,
            
        
    },
    {  
        id:8,
        title:'Cache',
        text: 'The party finds a Cache of supplies left behind by other explorers.',
        monsters:false,
        name:"",
        rolls:0,
        die:0,
        extra:0,
            
        
    },
     { id: 9,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters:true, 
        name:'Tribal Warrior',
        rolls:3,
        die:6,
        extra:0
    
    },
      { id: 10,
        title: 'Cannibals',
        text: 'Chultan cannibals prowl the jungle in small groups, killing and eating zombies while steering clear of more powerful, faster undead.  Abandoned by their Gods, the cannibals have returned to worship Dendar the night Serpent and they pay tribute to Ras Nsi in exchange for his favor and protection.  They have a blue triangle painted on their forehead (Ras Nsi) and do venture into Omu.   Day: 3d6 Canibals feast on a zombie, the players see them.  Night: The cannibals sneak into the players camp.  DC10 Perception check by the player on guard notices.',
        monsters:true, 
        name:'Tribal Warrior',
        rolls:3,
        die:6,
        extra:0
    
    } ,
    {   id: 11,
        title: 'Allosaurus',
        text: 'Theparty scent atteracts 1d4-1 allorsaurus.  Any characters who succeed ona DC 15 Survival check find a safe place to hide, high branch, hole etc, where the "honkers" cant reach them',
        monsters:true, 
        name:'Allosaurus',
        rolls:1,
        die:4,
        extra:-1
    
    } ,
   
    { 
        id: 12,
        title: 'Ankylosaurus',
        text: 'An ornery Ankylosaurus (club tail dino) is gorging itself on plants and attacks any thing that gets in its way.',
        monsters:true, 
            name: "",
            rolls:1,
            die:0,
            extra:3,
    } ,

    { 
        id: 13,
        title: 'Deinonychus',
        text: 'A wild boar races bas the party being chased by 1d4+2 deinonychuses the predators decide the characters are more interesting than the prey.',
        monsters:true, 
            name: "Deinonychus",
            rolls:1,
            die:4,
            extra:2,
    },
    { 
        id: 14,
        title: 'Hadrosaurus',
        text: 'A herd of 3d6 hadrosauruses are grazing nearby with 1d6 non combatant young.  The adults dont attack onless attacked or antagonized.  The young are Small beasts that can be sold to Ifan Talroa in Port Nyanzaru for 50 gp each, or for 100gp each if the player succeeds ona dc 15 charisma check.  The young dinosaurs are easy to handle if seperated from their parents but the adults fight if their children are captured.',
        monsters:true, 
        name: "Hadrosaurus",
        rolls:3,
        die:6,
        extra:0,
    } ,
    { 
        id: 15,
        title: 'Pternadon',
        text: 'A fock of 2d6 Pternadon is spotted overhead.  They keep their distance and only attak if threatned',
        monsters:true, 
        name: "Pternadon",
        rolls:3,
        die:6,
        extra:0,
                }  ,
      { id: 16,
        title: 'Stegasourus',
        text: 'This lone stegosaurus is in a genial mood and approaches the characters out of curiosity.  Anyone who touches it triggers a swipe from its tail.',
        monsters:true, 
            name: "Stegasourus",
            rolls:2,
            die:6,
            extra:0,
        },
    { 
        id: 17,
        title: 'Triceratops',
        text: 'A triceratops who apperas to be grazing alone is actually a mother with a nearby nest containing one noncombatant hatchling and two unhatched eggs.  The mother eyes the characters supiciously but doesnt attack unless they position themselves between her and the nest.  Ifan Talor in Port Nyanzaru offers 50gp for a young triceratops or an intact egg.  Can be talked up to 150 gold on asuccessful Charisma check of 15',
        monsters:true, 
            name: "Triceratops",
            rolls:0,
            die:0,
            extra:1,
            
    } ,
      { id: 18,
        title: 'Tyranosaurus Rex',
        text: 'The characters spot a Tyranosaurus Rex 50 feet away.  On an even roll the dinosaur is locked in combat with a triceratops or stegasaurus, giant ape, a pair of giant constrictor snakes, or a mob of ghouls or zombies.  These mobs will not assist the players in any way directly but may weaken the creature so it can be killed by the players.  The characters can avoid the encounter with all players making a DC 15 stealth check.  If any player is proficient in the stealh skill all checks are made with advantage', 
        monsters:true, 
            name: "Tyranosaurus",
            rolls:1,
            die:10,
            extra:0,
        } ,
      { id: 19,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.'  + 
        "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check."  +
        "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters:true, 
            name: "Scout",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 20,
        title: 'Emerald Enclave',
        text: 'Thecharacters stumble upon a band of Emerald Enclave scouts OR one of their outposts.  Choose whichever works best.  SCOUTS: The party meets 1d4+1 members of the EMerald Enclave working to rid the jungle of its undead menace.  The group works with a priest of Mielikki, but all other members are scouts.'  + 
        "If on of the characters has died recently you can use this to introduce a new character, a member of the emerald enclave, one of the scouts, or someone who has hired the m or been rescued by them.  The scouts will trade information on an equal basis with a nopn evil party.  The scouts can also be convinced to join the party for three days by succeeding on a DC 12 group Charisma check."  +
        "OUTPOST: Any character with a  passive perception of 13 or higher spots a wooden platform in a tree 2d6 * 5 feet in the air and requires a dc 12 strength check to climb.  The platform is sturdy and can hold up to six characters and their gear ",
        monsters:true, 
            name: "Scout",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 21,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.' ,
        monsters:true, 
            name:"Dead Adventurers",
            rolls:1,
            die:6,
            extra:0
        } ,
      { id: 22,
        title: 'Explorers, dead',
        text: 'Chult is strewn with the bones and bodies of those who have fallen victim to its terrors. Roll once on the dead adventureres table to see what the players have found, then once on the treasure table to acertain what the explorers were carrying.' ,
        monsters:true, 
            name:"Dead Adventurers",
            rolls:1,
            die:6,
            extra:0 
     },
      { id: 23,
        title: 'Explorers',
        text: 'Thepart runs upon another band of explorers consisting of a mage, a priest, a scout, and 1d6 tribal warriors.  Roll d6 to determine the groups situation.  1-2: Explorers are lost and hungry, 3-4 The eplxorers are in good shape but are actively being hunted by firenewts, ghouls, grungs, or goblins. 5 They are healthy and intent on epxloring the enarest landmark and are headed there.  6 they are healthy and headed  back to port Nyanzaru to resupply',
        monsters:true, 
            name:"Tribal Warrior",
            rolls:1,
            die:6,
            extra:0
        }, 
      { id: 24,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters:true, 
            name:"guard",
            rolls:2,
            die:6,
            extra:0
        } ,
      { id: 25,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters:true, 
            name:"guard",
            rolls:2,
            die:6,
            extra:0
        } ,
      { id: 26,
        title: 'Flaming Fist',
        text: 'FLaing Fist know the jungle dangers better than most.  A typical band consists of knight or veterna leading a band of 2d6 guards, a ascout, and an acolyte and 1d4 deinonychuses trained to fight and hunt alongside their handlers.   The band is friendly to anyone with a charter of exploration issued by Liara Portyr at Fort Belurian.  Otherwise, the band attempts to confiscate the partys gear and tells them to resupply at Fort Beluarian',
        monsters:true, 
            name:"guard",
            rolls:2,
            die:6,
            extra:0
        } ,
      { id: 27,
        title: 'Fyling Snakes',
        text: 'Roll any die.  On even the party encounters 1 flying snake, on odd they encounter 2d6 flying snakes.  These snakes only attack when threatened.  A flying snake that has been successfully grappled can be stuffed in a bag or container.  After 1 hour of confinement the snake calms down.  A character witha  DC 13 Animal Handling check can remove a calm snake form the container without causing it to attack or fly away.  Ifan Tal Roa will pay 25 gold per snake in Port Nyanzaru and cahn be convinced to buy them for 50g old ona  dc 15 charisma check ',
        monsters:true, 
            name:"Flying Snake",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 28,
        title: 'Giant Lizards',
        text: 'Thecharacters come across 1d6 giant lizards sunning themselves on warm rocks.  The lizards pose no threat to the characters unless threatened and are to set in their ways to be tamed',
        monsters:true, 
            name: "Giant Lizard",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 29,
        title: 'Giant Wasps',
        text: 'A droning sound announces the pressence of 1d6 Giant Wasps before the characters see them.  The Wasps all attack at once ignoring those with heavy armor in favor of those with limited or no armor.  Any character damaged by the wasps must make a DC 11 con save at the end of combat of contract Shivering Sickness',
        monsters:true, 
            name: "Giant Wasp",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 30,
        title: 'Girralons',
        text: 'Two Girallons (four-armed super gorillas) are spotted in the trees or lumnber between crumbling, vine-covered ruins.  The group can skirt past ona  DC 13 group stealth check. If the characters defeat, ro frighten the gorillons away a search of the area finds a hidden cache, roll on the cache table.  Also roll once on the treasure table to determine what the gorillans have stashed',
        monsters:true, 
            name: "Girralon",
            rolls:1,
            die:0,
            extra:2,
        } ,
      { id: 31,
        title: 'Velociraptors',
        text: 'A pck of 3d6 velociraptors burst from behind cover and attack. MAke a stealth check for the dinosaurs with advantage.  Any character whos passive wisdom is higher than the stealth check is not surprised',
        monsters:true, 
            name:"Velociraptor",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 32,
        title: 'Goblins',
        text: 'A Batari patrol of a goblin boss + 2d6+2 golbins all wearing painted wooden masks.  NIGHT: any player on watch must suceed on a dc 16 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised.  DAY:  Each player must make a DC 16 insight check to spot the signs of an ambush and an eerie silence in the jungle.  Othersiwse they are surprised.  Goblins will baragain for their lives and can be coerced or forced to serve as a guide with +1 survival.',
        monsters:true, 
            name: "Goblin",
            rolls:2,
            die:6,
            extra:2,
        } ,
      { id: 33,
        title: 'Goblins',
        text: 'A Batari patrol of a goblin boss + 2d6+2 golbins all wearing painted wooden masks.  NIGHT: any player on watch must suceed on a dc 16 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised.  DAY:  Each player must make a DC 16 insight check to spot the signs of an ambush and an eerie silence in the jungle.  Othersiwse they are surprised.  Goblins will baragain for their lives and can be coerced or forced to serve as a guide with +1 survival.',
        monsters:true, 
            name: "Goblin",
            rolls:2,
            die:6,
            extra:2,
        } ,
      { id: 34,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters:true, 
            name: "Grung",
            rolls:2,
            die:6,
            extra:1,
        } ,
      { id: 35,
        title: 'Grungs',
        text: 'A grung hunting party led by a Grung ELite Warrior and 2d6 grungs (frog people).  DAY:  A DC 14 perception check spots an ambush, otherwise the players are surprised.  NIGHT: any player on watch must suceed on a dc 14 perception check with disadvantage to spot the goblins setting up an ambush.  If no one succeed the entire party is suprised. If a grung is captured, he will offer to lead the characters to treasure in exchange for freedom.  The treasure is a cache one half mile from the players.  Roll once on the cahce table, ',
        monsters:true, 
            name: "Grung",
            rolls:2,
            die:6,
            extra:1,
        } ,
      { id: 36,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters:true, 
            name:"Mad Monkey Mist",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 37,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters:true, 
            name:"Mad Monkey Mist",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 38,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters:true, 
            name:"Mad Monkey Mist",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 39,
        title: 'Mad Monkey Mist',
        text: 'A blue mist floats toward the players covering 1d6 20 ft squares.  Any character with a passive wisdom of 13 spots the mist and can warn the other palyers.  At night, the mist drifts through camp at 5ft per round.  Characters who come in contact with the mist contract Mad Monkey Fever',
        monsters:true, 
            name:"Mad Monkey Mist",
            rolls:1,
            die:6,
            extra:0,
        } ,
      {id: 40,
        title: 'Mantraps',
        text: 'The characters wander into a patch of 1d4+1 mantraps (giant man eating plant). The plants are indistinguishable until they attack.  The plants are spaced 10 ft apart and must wait until players come close enough to attack.',
        monsters:true, 
            name:"Mantrap",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 41,
        title: 'Mantraps',
        text: 'The characters wander into a patch of 1d4+1 mantraps (giant man eating plant). The plants are indistinguishable until they attack.  The plants are spaced 10 ft apart and must wait until players come close enough to attack.',
        monsters:true, 
            name:"Mantrap",
            rolls:1,
            die:4,
            extra:1,
         },
      { id: 42,
        title: 'Night Hag',
        text: 'One of the Sewn Sisters (hags from the tomb of anihilation) has been following the party staying in the Border Ethereal.  During the partys next long rest, she materialzies, snatches one of the partys blood or hair and disappears returning to the ethereal plane.',
        monsters:true, 
            name:"Night Hag",
            rolls:1,
            die:0
            ,
            extra:0,
         },
      { id: 43,
        title: 'Pterrafolk',
        text: 'Looming in the sky 1d4+2 pterafolk watch the characters every move and wait until they blunder into danger, the next time an encounter occurs, the Pterafolk attack launching javelin attacks and staying out of melee range.  With firm resistance the pterafolk retreat but may regroup to attack at your discretion' ,
        monsters:true, 
            name:"Pterafolk",
            rolls:1,
            die:4,
            extra:2
        } ,
      { id: 44,
        title: 'Pterrafolk',
        text: 'Looming in the sky 1d4+2 pterafolk watch the characters every move and wait until they blunder into danger, the next time an encounter occurs, the Pterafolk attack launching javelin attacks and staying out of melee range.  With firm resistance the pterafolk retreat but may regroup to attack at your discretion' ,
        monsters:true, 
            name:"Pterafolk",
            rolls:1,
            die:4,
            extra:2
        } ,
      { id: 45,
        title: 'Rare Plant',
        text: 'The characters find one or more unusall plants determind by a d6 roll.  1  - 2d6 dancing monkey fruit growing on a tree. 2 - manga bush with 2d6 ounces of leaves.  3 - 1d4 ryath roots growing in gorund. 4 4d6 sindaberries growing in a bush.  5 - wukka tree with 2d6 wukka nuts.  6 1d6 zabu growing on a dead tree.',
        monsters:false, 
            name:"",
            rolls:1,
            die:6,
            extra:0
        } ,
      { id: 46,
        title: 'Red Wizard',
        text: 'This group consists of 1 red wizard, LE, human mage, 1d6 guards, and 1d6 skeletons, all answerable to Velinda Shadowmantle.  If this encounter happens outside of the city of Omu, they are reinforcements on their way to the city.  If inside Omu the party is searching the citry for shrines (chapter 3).  They are not spoiling for a fight and if things look grim, they will surrender and offer up a crudely drawn map of Chult with the location of known undead hordes.',
        monsters:true, 
            name:"Red Wizard",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 47,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"constrictor snake",
            rolls:0,
            die:0,
            extra:0
        } ,
      { id: 48,
        title: 'Snake, Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"constrictor snake",
            rolls:0,
            die:0,
            extra:0
        } ,
      { id: 49,
        title: 'Snake, Giant Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"Giant Constrictor Snake",
            rolls:2,
            die:6,
            extra:0
        } ,
      { id: 50,
       title: 'Snake, Giant Constrictor',
        text: 'A constrictor snake attacks a random party member from hiding.  The character is suprised unless their passive perception is greater than 11',
        monsters:true, 
            name:"Giant Constrictor Snake",
            rolls:2,
            die:6,
            extra:0,

         },
      { id: 51,
        title: 'Spiders',
        text: 'Giant spiderwbs are easily concealed in Chults dense jungles and swamps.  Passive perception of 13 or higher alerts the characeters in time for an encounter with 1d6 giant spiders.  Otherwise, the lead party member stumbles into an ambush and becomes grappled with a escape dc of 12 - the spiders have suprise and 100s of harmless baby spiders crawl through the webs', 
        monsters:true, 
            name:"Giant Spider",
            rolls:1,
            die:6,
            extra:0,

         },
      { id: 52,
        title: 'Spiders',
        text: 'Giant spiderwebs are easily concealed in Chults dense jungles and swamps.  Passive perception of 13 or higher alerts the characeters in time for an encounter with 1d6 giant spiders.  Otherwise, the lead party member stumbles into an ambush and becomes grappled with a escape dc of 12 - the spiders have suprise and 100s of harmless baby spiders crawl through the webs', 
        monsters:true, 
            name:"Giant Spider",
            rolls:1,
            die:6,
            extra:0,
         },
      { id: 53,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters:false, 
            name:"",
            rolls:2,
            die:6,
            extra:0,
        } ,
      {id: 54,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters:false, 
            name:"",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 55,
        title: 'Statue of Ubtao',
        text: 'see page 202',
        monsters:false, 
            name:"",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 56,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters:true, 
            name:"Stirge",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 57,
        title: 'Stirges',
        text: 'Chut is rich in caves, ruins, and hollow logs where stirges can hide.  By day, the party disturbs 2d6 stirges as they move through the jungke.  By night, the Stirges descend upon them',
        monsters:true, 
            name:"Stirge",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 58,
        title: 'Su Monster',
        text: 'the party comes across 1d4+1 su monsters.  The su monsters approach cautiuosly and if can get close use psychic blasts.  If the fight goes against them they retreat to their nest and have treasure.  Roll once on the treasure table to find out what it is.',
        monsters:true, 
            name: "Su Monster",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 59,
        title: 'Su Monster',
        text: 'the party comes across 1d4+1 su monsters.  The su monsters approach cautiuosly and if can get close use psychic blasts.  If the fight goes against them they retreat to their nest and have treasure.  Roll once on the treasure table to find out what it is.',
        monsters:true, 
            name: "Su Monster",
            rolls:1,
            die:4,
            extra:1,
        } ,
      { id: 60,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters:true, 
            name:"Swarm of Bats",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 61,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters:true, 
            name:"Swarm of Bats",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 62,
        title: 'Swarm of Bats',
        text: 'Ruis, hallow trees, and hidden caves all serve as hiding places for swarms of bats.  The party disturbs 1d4 swarm of bats that have become unnaturally aggressive after feasting on undead flesh',
        monsters:true, 
            name:"Swarm of Bats",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 63,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters:true, 
            name: "Swarm of Insects",
            rolls:2,
            die:6,
            extra:2,
        } ,
        { id: 64,
            title: 'Swarm of Insects',
            text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
            monsters:true, 
                name: "Swarm of Insects",
                rolls:2,
                die:6,
                extra:2,
            }  ,
      { id: 65,
        title: 'Swarm of Insects',
        text: 'The characters are beset bny 1d4 swams of centepedes.  Any cahracter damaged by a sawrm must suceed on a dc 11 con save or get SHIVERING SICKNESS',
        monsters:true, 
            name: "Swarm of Insects",
            rolls:2,
            die:6,
            extra:2,
        } ,
      { id: 66,
        title: 'Tri-flower frond',
        text: 'If his encounter happens in the wild the party stumbles upon 1d4 Tri-flower fronds that appear as nomral plants.  If the encounter occurs while the characters are camped, the fronds sneak into camp and attempt to anesthitize the party with their orange blossoms, then kill them with their yellow and red blossoms.',
        monsters:true, 
            name:"Tri-flower frond",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 67,
        title: 'Troll',
        text: 'A hungry troll comes crashing out of the jungle intent on eating the characters',
        monsters:true, 
            name: "Troll",
            rolls:1,
            die:6,
            extra:0,
        } ,
      { id: 68,
        title: 'Ghouls',
        text: 'Any passive perception 12 or hihger hears and smells a ghoul pack approaching consisting of 2d6 ghouls led by a ghast.  The Ghast has a blue triangle tattooed on its forehead indicator that it once served ras nsi.',
        monsters:true, 
            name:"Ghoul",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 69,
        title: 'Ghouls',
        text: 'Any passive perception 12 or hihger hears and smells a ghoul pack approaching consisting of 2d6 ghouls led by a ghast.  The Ghast has a blue triangle tattooed on its forehead indicator that it once served ras nsi.',
        monsters:true, 
            name:"Ghoul",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 70,
        title: 'Ghouls',
        text: 'Any passive perception 12 or hihger hears and smells a ghoul pack approaching consisting of 2d6 ghouls led by a ghast.  The Ghast has a blue triangle tattooed on its forehead indicator that it once served ras nsi.',
        monsters:true, 
            name:"Ghoul",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 71,
        title: 'Ghouls',
        text: 'Any passive perception 12 or hihger hears and smells a ghoul pack approaching consisting of 2d6 ghouls led by a ghast.  The Ghast has a blue triangle tattooed on its forehead indicator that it once served ras nsi.',
        monsters:true, 
            name:"Ghoul",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 72,
        title: 'Ghouls',
        text: 'Any passive perception 12 or hihger hears and smells a ghoul pack approaching consisting of 2d6 ghouls led by a ghast.  The Ghast has a blue triangle tattooed on its forehead indicator that it once served ras nsi.',
        monsters:true, 
            name:"Ghoul",
            rolls:2,
            die:6,
            extra:0,
        } ,
      { id: 73,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters:true, 
            name:"Skeleton",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 74,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters:true, 
            name:"Skeleton",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 75,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters:true, 
            name:"Skeleton",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 76,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters:true, 
            name:"Skeleton",
            rolls:3,
            die:6,
            extra:0,
         },
      { id: 77,
        title: 'Skeletons',
        text: 'The characters come across 3d6 skeletons.  If during travel, they lie on the ground and spring up waiting for passersby.  During camp they wander in on the party unawares.',
        monsters:true, 
            name:"Skeleton",
            rolls:3,
            die:6,
            extra:0,
         },
      { id: 78,
        title: 'Spectre',
        text: 'The evil remnant of a dead explorer has become a spectre that attacks the party.  His body can be found with a dc 13 survival check.  If found roll on the dead explorer check. ',
        monsters:true, 
            name:"Spectre",
            rolls:0,
            die:0,
            extra:3,
         },
      { id: 79,
        title: 'Spectre',
        text: 'The evil remnant of a dead explorer has become a spectre that attacks the party.  His body can be found with a dc 13 survival check.  If found roll on the dead explorer check. ',
        monsters:true, 
            name:"Spectre",
            rolls:0,
            die:0,
            extra:3,
         },
      { id: 80,
        title: 'Wight',
        text: 'The characters encounter a wight that has lurked int he chultan jungle since before the spell plague.  It hates all chultans and Ubtao especialy.  If any chultan or Ubtao symbols, the wight attacks them with preference.',
        monsters:true, 
            name:"Wight",
            rolls:0,
            die:0,
            extra:3,
         },
      { id: 81,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
         },
      { id: 82,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
         },
      { id: 83,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
         },
      { id: 84,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
         },
      { id: 85,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
        } ,
      { id: 86,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
        } ,
      { id: 87,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
        } ,
      { id: 88,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
        } ,
      { id: 89,
        title: 'Zombies',
        text: 'Characters catch the cent of death and hear the undead lumbering through the jungle.  Roll a d10.  1-3 3d6 Zombies.  4-5: One Ankylosaurus Zombie.  6-7  1d4 Giriallon Zombies.  8-9 1d4 Ogre Zombies.  10 Tyranosaurus zombie.',
        monsters:true, 
            name:"Zombie",
            rolls:1,
            die:10,
            extra:3,
        } ,
      { id: 90,
        title: 'Vegepygmy',
        text: 'The characters cross path with 1d4 vegepygmys each one mounted on a Thorny.  The hunters have wandered far from their tribe.  They flee if outnumbered otherwise they attack.',
        monsters:true, 
            name:"Vegepygmy",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 91,
        title: 'Vegepygmy',
        text: 'The characters cross path with 1d4 vegepygmys each one mounted on a Thorny.  The hunters have wandered far from their tribe.  They flee if outnumbered otherwise they attack.',
        monsters:true, 
            name:"Vegepygmy",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 92,
       title: 'Wereboar',
        text: 'A wereboar masquerading as a chultan priest takes a dim view of explorers encroaching on its territory.  On its neck is a wooden labrynth carved into a wooden disk.  The symbol of Ubtao.  He might be guarding a shrine to Ubtao a grove of wukka trees or a cave it uses as a lair.  It may also have treasure.  Roll 3 trasure drops in the trasure table.',
        monsters:true, 
            name:"Wereboar",
            rolls:0,
            die:0,
            extra:1, 
        } ,
      { id: 93,
        title: 'Weretiger',
        text: 'In human forma  weretiger offers to excort the party through a very dangerous stretch of wilderness.  If they accompany her, they cannot get attacked.  She will leave after 24 hours and will not go to Omu Nangalore or Orolunga.',
        monsters:true, 
            name:"Weretiger",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 94,
        title: 'Winterscape',
        text: 'The characters stumble intoa  112 ft radius sphere of winter weather.  Artus used the ring of winter to drive off monsters.  All plants are covered in glittering ice and frost.  The temperature in here is a biting -30 degrees farenhiet and cannot be dispelled.',
        monsters:false, 
            name:"",
            rolls:0,
            die:0,
            extra:1,
        } ,
      { id: 95,
        title: 'Yellow musk creeper and zombies',
        text: 'The characters pass close to a ruin inhabited by 3d6 Yellow Musk Zombies.  Somewhere within the ruin a Yellow Musk Creeper clings to a wall.  If this encounter occurs while the players are camped the zombies attack the camp and attempt to drag the party back to the ruin',
        monsters:true, 
            name:"Yellow Musk Creeper",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 96,
        title: 'Yellow musk creeper and zombies',
        text: 'The characters pass close to a ruin inhabited by 3d6 Yellow Musk Zombies.  Somewhere within the ruin a Yellow Musk Creeper clings to a wall.  If this encounter occurs while the players are camped the zombies attack the camp and attempt to drag the party back to the ruin',
        monsters:true, 
            name:"Yellow Musk Creeper",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 97,
        title: 'Yuan-ti',
        text: 'Yuan-ti patrols consist of 1d6+1 Yuan-ti purebloods who keep their distance while they try to gather information to bring back to Ras Nsi.  The Yuan-ti are disguised but any character who succeeds on a DC 13 Perception check made with disadvantage catches sight of the serpent folk as they withdraw. If within 25 miles of OMU the group is 1d4+1 yuan-ti Malisons instead and the check is DC 14',
        monsters:true, 
            name:"Yuan-ti",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 98,
        title: 'Yuan-ti',
        text: 'Yuan-ti patrols consist of 1d6+1 Yuan-ti purebloods who keep their distance while they try to gather information to bring back to Ras Nsi.  The Yuan-ti are disguised but any character who succeeds on a DC 13 Perception check made with disadvantage catches sight of the serpent folk as they withdraw. If within 25 miles of OMU the group is 1d4+1 yuan-ti Malisons instead and the check is DC 14',
        monsters:true, 
            name:"Yuan-ti",
            rolls:1,
            die:4,
            extra:0,
        } ,
      { id: 99,
        title: 'Zhentarim',
        text: 'A zhent assassin with a fling snake pet leads a priest, 2d6 thugs and 1d6 tribal warriors through the wilderness in search of Artus Cimber and The Ring of Winter.  If Artus is with the party the Zhents attack to get the ring otherwise they show little interest.  Roll on the treasure table to determine what if anything they carry',
        monsters:true, 
            name:"Assassin",
            rolls:3,
            die:6,
            extra:0,
        } ,
      { id: 100,
        title: 'Zorbos',
        text: 'If his encounter happens in the wild the party stumbled upon 2d6 Zorbos in wukka trees who attack if the party makes threatening motions.  If during camp, the Zorbos drop from surrounding trees and attack.',
        monsters:true, 
            name:"Zorbo",
            rolls:2,
            die:6,
            extra:0,
        },
    ]





